### ISSUE TITLE
Invalid config with new core-2021.6.3

### ISSUE THREAD

**Issue by Nory-01** [Silvest89/yeelight_v2#13]
Hello, 

I have done the update of HA, 2021.6.3, and since the integration is not functional.
I have this error: 

"The following integrations and platforms could not be set up:
 yeelight_v2"

**Comment by andres-fuentes** [comment]
In core-2021.6.4 the same error:

Logger: homeassistant.setup
Source: setup.py:172
First occurred: 19:53:53 (1 occurrences)
Last logged: 19:53:53

Setup failed for yeelight_v2: Integration not found.

**Comment by andres-fuentes** [comment]
I see it in https://www.home-assistant.io/blog/2021/06/02/release-20216/ :
```
Custom integrations (custom_components)
As mentioned in every release since 2021.3, custom integrations will require a version key in their manifest file.

As of this release, if that version key is missing in the manifest, the custom integration will no longer be loaded.

For more details see our developer blog about it

(@ludeeus - #49916)
```

**Comment by Nory-01** [comment]
Hello,

This modif has working fine for me.
https://github.com/Silvest89/yeelight_v2/issues/11

**Comment by Silvest89** [comment]
PR has been merged
